"use strict";this.default_IdentityRotateCookiesHttp=this.default_IdentityRotateCookiesHttp||{};(function(_){var window=this;
try{
_._F_toggles_initialize=function(a){(typeof globalThis!=="undefined"?globalThis:typeof self!=="undefined"?self:this)._F_toggles_default_IdentityRotateCookiesHttp=a||[]};(0,_._F_toggles_initialize)([0xc0000, ]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){h.setTimeout(()=>{throw a;},0)},l=function(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b},n=function(a){a=Error(a);l(a,"warning");return a},p=function(){return typeof BigInt==="function"},r=function(a,b=!1){return b&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol()},v=function(a,b){return b===void 0?a.i!==t&&!!(2&(a.h[u]|0)):!!(2&b)&&a.i!==t},w=function(a){a.v=!0;return a},C=function(a){var b=
a;if(x(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(ba(b)&&!Number.isSafeInteger(b))throw Error(String(b));return B?BigInt(a):a=ca(a)?a?"1":"0":x(a)?a.trim()||"0":String(a)},da=function(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(let c=0;c<a.length;c++){const d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}},ea=function(a){const b=a>>>0;D=b;E=(a-b)/4294967296>>>0},H=function(a){if(a<0){ea(-a);const [b,c]=G(D,E);D=b>>>0;E=c>>>0}else ea(a)},
I=function(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else p()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+fa(c)+fa(a));return c},fa=function(a){a=String(a);return"0000000".slice(a.length)+a},ha=function(){var a=D,b=E;if(b&2147483648)if(p())a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0));else{const [c,d]=G(a,b);a="-"+I(c,d)}else a=I(a,
b);return a},G=function(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]},ia=function(a,b=`unexpected value ${a}!`){throw Error(b);},la=function(a){switch(typeof a){case "bigint":return!0;case "number":return ja(a);case "string":return ka.test(a);default:return!1}},ua=function(a){var b=void 0;b!=null||(b=ma?1024:0);if(!la(a))throw n("int64");const c=typeof a;switch(b){case 512:switch(c){case "string":return na(a);case "bigint":return String(J(64,a));default:return oa(a)}case 1024:switch(c){case "string":return ra(a);
case "bigint":return C(J(64,a));default:return sa(a)}case 0:switch(c){case "string":return na(a);case "bigint":return C(J(64,a));default:return ta(a)}default:return ia(b,"Unknown format requested type for int64")}},va=function(a){var b=a.length;if(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")return a;if(a.length<16)H(Number(a));else if(p())a=BigInt(a),D=Number(a&BigInt(4294967295))>>>0,E=Number(a>>BigInt(32)&BigInt(4294967295));else{b=+(a[0]==="-");E=D=
0;const c=a.length;for(let d=b,e=(c-b)%6+b;e<=c;d=e,e+=6){const f=Number(a.slice(d,e));E*=1E6;D=D*1E6+f;D>=4294967296&&(E+=Math.trunc(D/4294967296),E>>>=0,D>>>=0)}if(b){const [d,e]=G(D,E);D=d;E=e}}return ha()},ta=function(a){a=K(a);if(!L(a)){H(a);var b=D,c=E;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);const d=c*4294967296+(b>>>0);b=Number.isSafeInteger(d)?d:I(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a},oa=function(a){a=K(a);L(a)?a=String(a):(H(a),a=ha());return a},na=function(a){var b=
K(Number(a));if(L(b))return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return va(a)},ra=function(a){var b=K(Number(a));if(L(b))return C(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return p()?C(J(64,BigInt(a))):C(va(a))},sa=function(a){return L(a)?C(ta(a)):C(oa(a))},wa=function(a){const b=typeof a;if(a==null)return a;if(b==="bigint")return C(J(64,a));if(la(a))return b==="string"?ra(a):sa(a)},xa=function(a){return a},M=function(a,b,c,d){var e=d!==void 0;d=!!d;const f=[];var k=a.length;
let g,m=4294967295,pa=!1;const F=!!(b&64),y=F?b&128?0:-1:void 0;if(!(b&1||(g=k&&a[k-1],g!=null&&typeof g==="object"&&g.constructor===Object?(k--,m=k):g=void 0,!F||b&128||e))){pa=!0;var q;m=((q=ya)!=null?q:xa)(m-y,y,a,g,void 0)+y}b=void 0;for(e=0;e<k;e++)if(q=a[e],q!=null&&(q=c(q,d))!=null)if(F&&e>=m){const z=e-y;let A;((A=b)!=null?A:b={})[z]=q}else f[e]=q;if(g)for(let z in g){a=g[z];if(a==null||(a=c(a,d))==null)continue;k=+z;let A;if(F&&!Number.isNaN(k)&&(A=k+y)<m)f[A]=a;else{let qa;((qa=b)!=null?
qa:b={})[z]=a}}b&&(pa?f.push(b):f[m]=b);return f},Aa=function(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return za(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){const b=a[u]|0;return a.length===0&&b&1?void 0:M(a,b,Aa)}if(a!=null&&a[N]===O)return P(a);return}return a},P=function(a){a=a.h;return M(a,a[u]|0,Aa)},Da=function(a,b,c,d=0){if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("a");
e=a[u]|0;if(Ba&&1&e)throw Error("b");2048&e&&!(2&e)&&Ca();if(e&256)throw Error("c");if(e&64)return(e|d)!==e&&(a[u]=e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("d");a:{c=a;e|=64;var f=c.length;if(f){var k=f-1;const m=c[k];if(m!=null&&typeof m==="object"&&m.constructor===Object){b=e&128?0:-1;k-=b;if(k>=1024)throw Error("f");for(var g in m)if(f=+g,f<k)c[f+b]=m[g],delete m[g];else break;e=e&-16760833|(k&1023)<<14;break a}}if(b){g=Math.max(b,f-(e&128?0:-1));if(g>1024)throw Error("g");e=e&-16760833|(g&1023)<<
14}}}a[u]=e|64|d;return a},Ca=function(){if(Ba)throw Error("e");if(Q!=null){var a;var b=(a=Ea)!=null?a:Ea={};a=b[Q]||0;a>=5||(b[Q]=a+1,b=Error(),l(b,"incident"),aa(b))}},Fa=function(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[u]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=R(a,c,!1,b&&!(c&16)):(a[u]|=34,c&4&&Object.freeze(a)));return a}if(a!=null&&a[N]===O){c=a.h;const d=c[u]|0;v(a,d)||(d&2?b=!0:d&32&&!(d&4096)?(c[u]=d|2,a.i=t,b=!0):b=!1,b?(a=new a.constructor(c),a.u=
t):a=R(c,d));return a}},R=function(a,b,c,d){d!=null||(d=!!(34&b));a=M(a,b,Fa,d);d=32;c&&(d|=2);b=b&16769217|d;a[u]=b;return a},Ga=function(a){return za(a)?Number(a):String(a)};var h=this||self,Ha=function(a){a:{var b=["WIZ_global_data","oxN3nb"];for(var c=h,d=0;d<b.length;d++)if(c=c[b[d]],c==null){b=null;break a}b=c}a=b&&b[a];return a!=null?a:!0},S=h._F_toggles_default_IdentityRotateCookiesHttp||[];var Ia=!!(S[0]>>19&1),Ja=!!(S[0]>>14&1),Ka=!!(S[0]&512),La=!!(S[0]&2048);var Ba=Ia?Ja||!Ka:Ha(748402147),ma=Ia?Ja||!La:Ha(824656860);var Ea=void 0;var Q=r(),N=r("m_m",!0);var u=r("jas",!0);var O={},t={},Ma={};var ba=w(a=>typeof a==="number"),x=w(a=>typeof a==="string"),ca=w(a=>typeof a==="boolean");var B=typeof h.BigInt==="function"&&typeof h.BigInt(0)==="bigint";var za=w(a=>B?a>=Na&&a<=Oa:a[0]==="-"?da(a,Pa):da(a,Qa)),Pa=Number.MIN_SAFE_INTEGER.toString(),Na=B?BigInt(Number.MIN_SAFE_INTEGER):void 0,Qa=Number.MAX_SAFE_INTEGER.toString(),Oa=B?BigInt(Number.MAX_SAFE_INTEGER):void 0;var D=0,E=0;var J=typeof BigInt==="function"?BigInt.asIntN:void 0,L=Number.isSafeInteger,ja=Number.isFinite,K=Math.trunc,ka=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;var ya;var Ra=C(0),Sa=function(a,b){a:{a=a.h;var c=1+(Ma?0:-1),d=a.length-1;if(d<1+(Ma?0:-1))var e=void 0;else{if(c>=d)if(e=a[d],e!=null&&typeof e==="object"&&e.constructor===Object){d=e[1];var f=!0}else if(c===d)d=e;else{e=void 0;break a}else d=a[c];if(b&&d!=null){b=b(d);if(b==null){e=b;break a}if(!Object.is(b,d)){f?e[1]=b:a[c]=b;e=b;break a}}e=d}}if(e!==null)return e},Ta=function(a,b,c){if(a.i===t){var d=a.h;d=R(d,d[u]|0);d[u]|=2048;a.h=d;a.i=void 0;a.u=void 0;d=!0}else d=!1;if(!d&&v(a,a.h[u]|0))throw Error();
d=a.h;a:{var e=d[u]|0;const f=b+-1,k=d.length-1;if(k>=0&&f>=k){const g=d[k];if(g!=null&&typeof g==="object"&&g.constructor===Object){g[b]=c;break a}}f<=k?d[f]=c:c!==void 0&&(e=(e!=null?e:d[u]|0)>>14&1023||536870912,b>=e?c!=null&&(d[e+-1]={[b]:c}):d[f]=c)}return a},Ua=function(a){a=ma?Sa(a,wa):wa(Sa(a));return a!=null?a:Ra},T=function(a,b,c){if(c!=null){if(typeof c!=="number")throw n("int32");if(!ja(c))throw n("int32");c|=0}Ta(a,b,c)};var U=class{constructor(a,b,c){this.h=Da(a,b,c,2048)}toJSON(){return P(this)}};U.prototype[N]=O;U.prototype.toString=function(){return this.h.toString()};var Va=class extends U{constructor(a){super(a)}};var Wa=function(a){return b=>{if(b==null||b=="")b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error("h");b[u]|=32;b=new a(b)}return b}}(class extends U{constructor(a){super(a,0,"identity.hfcr")}});var Xa=function(a){a={method:"POST",credentials:"same-origin",cache:"no-store",mode:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(P(a))};if(typeof AbortController!=="undefined"){const b=new AbortController;setTimeout(()=>{b.abort()},3E4);a.signal=b.signal}return fetch(new Request("/RotateCookies",a)).then(b=>b.text()).then(b=>Wa(JSON.stringify(JSON.parse(b.substring(5))[0])))},Ya=function(){try{const a=window.localStorage;if(!a)return!1;a.setItem("cookieRotationStorageAccessTest",
"1");a.removeItem("cookieRotationStorageAccessTest");return!0}catch(a){return!1}},V=function(){try{const a=window.localStorage.getItem("nextRotationAttemptTs");if(!a)return null;const b=Math.floor(Number(a));return Number.isNaN(b)?null:b}catch(a){return null}},W=function(a){try{window.localStorage.setItem("nextRotationAttemptTs",a.toString())}catch(b){}},$a=function(a){const b=V();if(!b||Date.now()>=b){const c=Math.floor(Math.random()*1E3);return new Promise(d=>{setTimeout(()=>{const e=V();!e||Date.now()>=
e?d(Za(a)):d()},c)})}return Promise.resolve()},bb=function(a){ab(a).then(()=>{const b=()=>{ab(a).then(()=>{setTimeout(b,a.g*1E3)})};setTimeout(()=>{b()},a.g*1E3)})},ab=function(a){const b=cb(a);return Xa(b).then(c=>{c=db(Ga(Ua(c)));c!==a.g&&(a.g=c)}).catch(()=>{a.g*=2})},cb=function(a){var b=new Va;var c=a.o;c=c==null?c:ua(c);b=Ta(b,2,c);a.l!==0&&T(b,1,a.l);a.m!==0&&T(b,3,a.m);a.j!==0&&T(b,4,a.j);return b},db=function(a){a<60&&(a=60);return a},Za=function(a){W(Date.now()+a.g*1E3);const b=cb(a);return Xa(b).then(c=>
{c=db(Ga(Ua(c)));c!==a.g&&(W(Date.now()+c*1E3),a.g=c)}).catch(()=>{a.g*=2;W(Date.now()+a.g*1E3)})},eb=class{constructor(a,b,c,d,e){this.o=a;this.l=b;this.m=c;this.j=d;this.g=e}start(){if(typeof fetch!=="undefined")if(Ya()){var a=V(),b=Date.now();a&&a>b+this.g*1E3&&(a=Date.now()+this.g*1E3,W(a));var c=()=>{$a(this).then(()=>{setTimeout(c,this.g*1E3)})};setTimeout(()=>{c()},a&&a>b?a-b:0)}else bb(this)}};for(var fb=function(a,b,c,d,e){(new eb(a,b,c,d,e)).start()},X=["init"],Y=h,Z;X.length&&(Z=X.shift());)X.length||fb===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=fb;
}catch(e){_._DumpException(e)}
}).call(this,this.default_IdentityRotateCookiesHttp);
// Google Inc.
